name: SonarCloud CI

on:
  push:
    # Trigger per push su tutti i branch
    branches:
      - main
      - master
      - '**'
  pull_request:
    # Trigger per Pull Request
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Cloni completi necessari per un'analisi SonarCloud più accurata
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install system dependencies (Linux)
        run: |
          sudo apt-get update
          # Le dipendenze di sistema installate (come 'xvfb') non sono più strettamente necessarie senza i test
          # ma le lasciamo in caso siano richieste da altre dipendenze Python.
          sudo apt-get install -y \
            libegl1 \
            libopengl0 \
            libdbus-1-3 \
            libxkbcommon-x11-0 \
            libxcb-cursor0 \
            libxcb-icccm4 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-randr0 \
            libxcb-render0 \
            libxcb-render-util0 \
            libxcb-shape0 \
            libxcb-shm0 \
            libxcb-sync1 \
            libxcb-xfixes0 \
            libxcb-xinerama0 \
            libxcb-xkb1 \
            libxcb-xinput0 \
            libx11-xcb1 \
            xvfb

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Installa tutte le dipendenze del progetto
          pip install -r requirements.txt

      - name: SonarCloud Scan
        # Questo step avvierà la scansione subito dopo l'installazione delle dipendenze.
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}